-- =============================================================================
-- hyprland.lua
-- Main Hyprland configuration entry point
-- Hyprland 0.55+ (Lua config)
-- Verified against 0.55.0 wiki and example config
-- =============================================================================

-- =============================================================================
-- LOAD COLORS (generated by wallust, must be first)
-- =============================================================================
require("colors")

-- =============================================================================
-- LOOK AND FEEL
-- =============================================================================
hl.config({
    general = {
        gaps_in          = 4,
        gaps_out         = 8,
        border_size      = 2,
        resize_on_border = true,
        layout           = "dwindle",

        col = {
            active_border   = "rgba(5f8aabee)",
            inactive_border = "rgba(373b41aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding         = 8,
        active_opacity   = 1.0,
        inactive_opacity = 0.92,

        blur = {
            enabled           = true,
            size              = 4,
            passes            = 2,
            new_optimizations = true,
        },

        shadow = {
            enabled      = true,
            range        = 12,
            render_power = 3,
        },
    },
})

hl.config({
    animations = {
        enabled = true
    },
})

-- =============================================================================
-- INPUT
-- =============================================================================
hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll      = true,
            drag_lock           = true,
        },
    },
})

-- Gestures use hl.gesture() in 0.55, NOT hl.config({ gestures = {} })
hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

-- =============================================================================
-- LAYOUT
-- =============================================================================
hl.config({
    dwindle = {
        preserve_split = true,
        smart_split    = false,
    },
})

-- =============================================================================
-- MISC
-- =============================================================================
hl.config({
    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
    },
})

-- =============================================================================
-- MONITOR
-- Managed by hyprdynamicmonitors
-- Configure with: hyprdynamicmonitors tui
-- Fallback for any display not covered by a saved profile
-- =============================================================================
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- =============================================================================
-- ENVIRONMENT VARIABLES
-- =============================================================================
hl.env("XCURSOR_SIZE",                        "24")
hl.env("XCURSOR_THEME",                       "Bibata-Modern-Classic")
hl.env("QT_QPA_PLATFORM",                     "wayland")
hl.env("QT_QPA_PLATFORMTHEME",                "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GDK_BACKEND",                         "wayland,x11")
hl.env("SDL_VIDEODRIVER",                     "wayland")
hl.env("CLUTTER_BACKEND",                     "wayland")
hl.env("XDG_CURRENT_DESKTOP",                 "Hyprland")
hl.env("XDG_SESSION_TYPE",                    "wayland")
hl.env("XDG_SESSION_DESKTOP",                 "Hyprland")
hl.env("MOZ_ENABLE_WAYLAND",                  "1")

-- =============================================================================
-- MODULES
-- =============================================================================
require("autostart")
require("keybinds")
require("windowrules")
