-- =============================================================================
-- hyprland.lua
-- Main Hyprland configuration entry point
-- Hyprland 0.55+ (Lua config)
-- =============================================================================

-- Remove this line once you have reviewed the config:

-- =============================================================================
-- LOAD COLORS (generated by wallust, must be first)
-- =============================================================================
require("colors")

-- =============================================================================
-- CORE SETTINGS
-- =============================================================================
hl.config({
    general = {
        gaps_in             = 4,
        gaps_out            = 8,
        border_size         = 2,
        resize_on_border    = true,
        layout              = "dwindle",
    },

    decoration = {
        rounding            = 8,
        active_opacity      = 1.0,
        inactive_opacity    = 0.92,

        blur = {
            enabled         = true,
            size            = 4,
            passes          = 2,
            new_optimizations = true,
        },

        shadow = {
            enabled         = true,
            range           = 12,
            render_power    = 3,
        },
    },

    animations = {
        enabled             = true,
        first_launch_animation = true,
    },

    input = {
        kb_layout           = "us",
        follow_mouse        = 1,
        sensitivity         = 0,

        touchpad = {
            natural_scroll      = true,
            tap-to-click        = true,
            drag_lock           = true,
        },
    },

    gestures = {
        workspace_swipe         = true,
        workspace_swipe_fingers = 3,
    },

    dwindle = {
        pseudotile          = false,
        preserve_split      = true,
        smart_split         = false,
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,
        vfr                     = true,
    },

    render = {
        new_render_scheduling = true,
    },
})

-- =============================================================================
-- MONITOR
-- Managed by hyprdynamicmonitors
-- Configure with: hyprdynamicmonitors tui
-- Profiles saved to ~/.config/hypr/monitors.conf
-- =============================================================================

-- Fallback for unknown displays
hl.monitor({ name = "", resolution = "preferred", position = "auto", scale = 1 })

-- =============================================================================
-- ENVIRONMENT VARIABLES
-- =============================================================================
hl.env("XCURSOR_SIZE",          "24")
hl.env("XCURSOR_THEME",         "Bibata-Modern-Classic")
hl.env("QT_QPA_PLATFORM",       "wayland")
hl.env("QT_QPA_PLATFORMTHEME",  "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GDK_BACKEND",           "wayland,x11")
hl.env("SDL_VIDEODRIVER",        "wayland")
hl.env("CLUTTER_BACKEND",        "wayland")
hl.env("XDG_CURRENT_DESKTOP",   "Hyprland")
hl.env("XDG_SESSION_TYPE",      "wayland")
hl.env("XDG_SESSION_DESKTOP",   "Hyprland")
hl.env("MOZ_ENABLE_WAYLAND",    "1")

-- =============================================================================
-- SPLIT CONFIG INTO MODULES
-- Each require() is a separate scope — errors in one don't break others
-- =============================================================================
require("autostart")
require("keybinds")
require("windowrules")
