-- =============================================================================
-- hyprland.lua
-- Main Hyprland configuration entry point
-- Hyprland 0.55+ (Lua config)
-- Verified against 0.55.0 wiki and example config
-- =============================================================================

-- =============================================================================
-- LOAD COLORS (generated by wallust, must be first)
-- =============================================================================
require("colors")

-- =============================================================================
-- LOOK AND FEEL
-- =============================================================================
hl.config({
    general = {
        gaps_in          = 4,
        gaps_out         = 8,
        border_size      = 2,
        resize_on_border = true,
        layout           = "dwindle",

        col = {
            active_border   = "rgba(5f8aabee)",
            inactive_border = "rgba(373b41aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding         = 8,
        active_opacity   = 1.0,
        inactive_opacity = 0.92,

        blur = {
            enabled           = true,
            size              = 4,
            passes            = 2,
        },

        shadow = {
            enabled      = true,
            range        = 12,
            render_power = 3,
        },
    },
})

hl.config({
    animations = {
        enabled = true
    },
})

-- =============================================================================
-- INPUT
-- =============================================================================
hl.config({
    input = {
        kb_layout    = "us",
        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll      = true,
            drag_lock           = true,
        },
    },
})

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

-- =============================================================================
-- LAYOUT
-- =============================================================================
hl.config({
    dwindle = {
        preserve_split = true,
        smart_split    = false,
    },
})

-- =============================================================================
-- MISC
-- =============================================================================
hl.config({
    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
    },
})

-- =============================================================================
-- MONITOR
-- =============================================================================
hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0",     scale = 1 })
hl.monitor({ output = "DP-4",  mode = "1920x1080@60", position = "-1080x0", scale = 1, transform = 3 })
hl.monitor({ output = "DP-6",  mode = "3840x2160@30", position = "0x-2160", scale = 1 })
hl.monitor({ output = "",      mode = "preferred",    position = "auto",    scale = 1 })

-- =============================================================================
-- ENVIRONMENT VARIABLES
-- =============================================================================
hl.env("XCURSOR_SIZE",                        "24")
hl.env("XCURSOR_THEME",                       "Bibata-Modern-Classic")
hl.env("QT_QPA_PLATFORM",                     "wayland")
hl.env("QT_QPA_PLATFORMTHEME",                "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GDK_BACKEND",                         "wayland,x11")
hl.env("SDL_VIDEODRIVER",                     "wayland")
hl.env("CLUTTER_BACKEND",                     "wayland")
hl.env("XDG_CURRENT_DESKTOP",                 "Hyprland")
hl.env("XDG_SESSION_TYPE",                    "wayland")
hl.env("XDG_SESSION_DESKTOP",                 "Hyprland")
hl.env("MOZ_ENABLE_WAYLAND",                  "1")
-- =============================================================================
-- MONITOR EVENTS
-- Re-apply layout on hotplug, pin default workspace per monitor
-- =============================================================================
hl.on("monitor.added", function(m)
    hl.timer(function()
        local mon = hl.get_monitor(m.name)
        if mon ~= nil and mon.active_workspace ~= nil then
            hl.workspace_rule({
                workspace  = tostring(mon.active_workspace.id),
                persistent = true,
                default    = true,
                monitor    = m.name
            })
        end
    end, { timeout = 500, type = "oneshot" })
end)

hl.on("monitor.removed", function(m)
    local workspaces = hl.get_workspaces()
    for _, ws in ipairs(workspaces) do
        if ws.monitor.name == m.name then
            hl.workspace_rule({ workspace = tostring(ws.id), persistent = false })
        end
    end
end)

hl.on("hyprland.start", function()
    hl.timer(function()
        local mon = hl.get_monitor("eDP-1")
        if mon ~= nil and mon.active_workspace ~= nil then
            hl.workspace_rule({
                workspace  = tostring(mon.active_workspace.id),
                persistent = true,
                default    = true,
                monitor    = "eDP-1"
            })
        end
    end, { timeout = 500, type = "oneshot" })
end)

-- =============================================================================
-- MODULES
-- =============================================================================
require("autostart")
require("keybinds")
require("windowrules")
