-- =============================================================================
-- hyprland-colors.lua
-- Generated by wallust — do not edit manually
-- =============================================================================

colors = {
    background      = "{{background}}",
    foreground      = "{{foreground}}",
    cursor          = "{{cursor}}",

    color0          = "{{color0}}",
    color1          = "{{color1}}",
    color2          = "{{color2}}",
    color3          = "{{color3}}",
    color4          = "{{color4}}",
    color5          = "{{color5}}",
    color6          = "{{color6}}",
    color7          = "{{color7}}",
    color8          = "{{color8}}",
    color9          = "{{color9}}",
    color10         = "{{color10}}",
    color11         = "{{color11}}",
    color12         = "{{color12}}",
    color13         = "{{color13}}",
    color14         = "{{color14}}",
    color15         = "{{color15}}",

    -- Semantic aliases built from the 16-color palette
    accent          = "{{color4}}",   -- primary accent (blue family)
    accent2         = "{{color2}}",   -- secondary accent (green family)
    border_active   = "{{color4}}",
    border_inactive = "{{color8}}",
    surface         = "{{color0}}",
    surface2        = "{{color8}}",
}

-- Apply border colors to Hyprland
hl.config({
    general = {
        col = {
            active_border   = colors.border_active,
            inactive_border = colors.border_inactive,
        }
    },
    decoration = {
        shadow = {
            color = "rgba(0,0,0,0.6)",
        }
    }
})
